# # Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# # More GitHub Actions for Azure: https://github.com/Azure/actions

# name: Build and deploy Node.js app to Azure Web App - ReactDemoAppDeploy

# on:
#   push:
#     branches:
#       - main
#   workflow_dispatch:

# jobs:
#   build:
#     runs-on: windows-latest
#     permissions:
#       contents: read #This is required for actions/checkout

#     steps:
#       - uses: actions/checkout@v4

#       - name: Set up Node.js version
#         uses: actions/setup-node@v3
#         with:
#           node-version: '20.x'

#       - name: npm install, build, and test
#         run: |
#           npm install
#           npm run build --if-present
#           npm run test --if-present
      
#       - name: Upload artifact for deployment job
#         uses: actions/upload-artifact@v4
#         with:
#           name: node-app
#           path: .

#   deploy:
#     runs-on: ubuntu-latest
#     needs: build
#     environment:
#       name: 'Production'
#       url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
#     steps:
#       - name: Download artifact from build job
#         uses: actions/download-artifact@v4
#         with:
#           name: node-app
      
#       - name: 'Deploy to Azure Web App'
#         uses: azure/webapps-deploy@v3
#         id: deploy-to-webapp
#         with:
#           app-name: 'ReactDemoAppDeploy'
#           slot-name: 'Production'
#           package: .
#           publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_3A67B4DF71C4431FBE051F9A0DDAB0AB }}


# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - ReactDemoAppDeploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      # Debug: List files in root directory
      - name: List files in root directory
        run: ls -la
        working-directory: .

      # Debug: List files in mern-user-crud directory
      - name: List files in mern-user-crud directory
        run: ls -la
        working-directory: ./mern-user-crud

      # Debug: List files in backend directory
      - name: List files in backend directory
        run: ls -la
        working-directory: ./mern-user-crud/backend

      # Install backend dependencies (mern-user-crud/backend directory)
      - name: Install backend dependencies
        run: |
          npm install
        working-directory: ./mern-user-crud/backend
        continue-on-error: false # Fail if package.json is missing in backend

      # Install frontend dependencies and build (mern-user-crud/frontend directory)
      - name: Install frontend dependencies and build
        run: |
          npm install
          npm run build
        working-directory: ./mern-user-crud/frontend
        continue-on-error: false # Fail if package.json is missing in frontend

      # Upload artifact for deployment job
      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: |
            ./mern-user-crud/backend # Include the backend directory (server.js, node_modules, etc.)
            ./mern-user-crud/frontend/dist # Include the frontend build output
            !./mern-user-crud/backend/node_modules # Exclude backend node_modules to reduce artifact size
            !./mern-user-crud/frontend/node_modules # Exclude frontend node_modules to reduce artifact size

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'ReactDemoAppDeploy'
          slot-name: 'Production'
          package: .
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_3A67B4DF71C4431FBE051F9A0DDAB0AB }}